import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useLanguage } from '@/contexts/LanguageContext';
import { Edit, History } from 'lucide-react';
import { FeedbackDropdown } from '@/components/FeedbackDropdown';
import { toast } from 'sonner';

interface DescriptionComparisonProps {
  selectedReviews: string[];
  selectedLanguages: string[];
  keywords?: string;
  canPublish: boolean;
}

export function DescriptionComparison({ 
  selectedReviews, 
  selectedLanguages,
  keywords,
  canPublish 
}: DescriptionComparisonProps) {
  const { t } = useLanguage();
  const [isEditingFr, setIsEditingFr] = useState(false);
  const [isEditingEn, setIsEditingEn] = useState(false);
  const [feedbackFr, setFeedbackFr] = useState<number | null>(null);
  const [feedbackEn, setFeedbackEn] = useState<number | null>(null);
  
  const [suggestedDescriptionFr, setSuggestedDescriptionFr] = useState(
    "Cette description optimisée a été générée par l'IA en analysant les avis clients. Elle met en avant les points forts du produit et répond aux préoccupations exprimées dans les avis."
  );
  const [suggestedDescriptionEn, setSuggestedDescriptionEn] = useState(
    "This optimized description was generated by AI by analyzing customer reviews. It highlights the product's strengths and addresses concerns expressed in the reviews."
  );

  const originalDescription = "Description originale du produit standard sans optimisation basée sur les avis clients.";
  
  const hasFrench = selectedLanguages.includes('fr');
  const hasEnglish = selectedLanguages.includes('en');
  
  const canPublishNow = canPublish && 
    ((hasFrench && feedbackFr !== null) || (hasEnglish && feedbackEn !== null));

  const handlePublish = () => {
    toast.success(
      canPublish
        ? 'Description publiée sur Shopify avec succès!'
        : 'Évaluation enregistrée!'
    );
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>{t('review.original')}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm max-w-none">
            <p className="text-muted-foreground">{originalDescription}</p>
          </div>
        </CardContent>
      </Card>

      {hasFrench && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              {t('review.suggestedFr')}
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsEditingFr(!isEditingFr)}
                >
                  <Edit className="h-4 w-4 mr-2" />
                  {t('review.modify')}
                </Button>
                <Button variant="outline" size="sm">
                  <History className="h-4 w-4 mr-2" />
                  {t('review.history')}
                </Button>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {isEditingFr ? (
              <Textarea
                value={suggestedDescriptionFr}
                onChange={(e) => setSuggestedDescriptionFr(e.target.value)}
                className="min-h-[200px]"
              />
            ) : (
              <div className="prose prose-sm max-w-none">
                <p className="text-foreground">{suggestedDescriptionFr}</p>
              </div>
            )}
            
            <div className="pt-4 border-t">
              <label className="text-sm font-medium mb-2 block">
                {t('review.feedback')}
              </label>
              <FeedbackDropdown value={feedbackFr} onChange={setFeedbackFr} />
            </div>
          </CardContent>
        </Card>
      )}

      {hasEnglish && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              {t('review.suggestedEn')}
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsEditingEn(!isEditingEn)}
                >
                  <Edit className="h-4 w-4 mr-2" />
                  {t('review.modify')}
                </Button>
                <Button variant="outline" size="sm">
                  <History className="h-4 w-4 mr-2" />
                  {t('review.history')}
                </Button>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {isEditingEn ? (
              <Textarea
                value={suggestedDescriptionEn}
                onChange={(e) => setSuggestedDescriptionEn(e.target.value)}
                className="min-h-[200px]"
              />
            ) : (
              <div className="prose prose-sm max-w-none">
                <p className="text-foreground">{suggestedDescriptionEn}</p>
              </div>
            )}
            
            <div className="pt-4 border-t">
              <label className="text-sm font-medium mb-2 block">
                {t('review.feedback')}
              </label>
              <FeedbackDropdown value={feedbackEn} onChange={setFeedbackEn} />
            </div>
          </CardContent>
        </Card>
      )}

      {canPublish && (
        <div className="flex justify-end">
          <Button
            disabled={!canPublishNow}
            onClick={handlePublish}
            size="lg"
          >
            {t('review.publish')}
          </Button>
        </div>
      )}

      {!canPublish && (
        <div className="flex justify-end">
          <Button
            disabled={(hasFrench && feedbackFr === null) || (hasEnglish && feedbackEn === null)}
            onClick={handlePublish}
            variant="secondary"
            size="lg"
          >
            Enregistrer l'évaluation
          </Button>
        </div>
      )}
    </div>
  );
}
