import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Auth
    'auth.login': 'Connexion',
    'auth.email': 'Courriel',
    'auth.password': 'Mot de passe',
    'auth.submit': 'Se connecter',
    'auth.forgotPassword': 'J\'ai oublié mon mot de passe',
    'auth.createAccount': 'Je veux créer mon compte',
    'auth.signup': 'Créer un compte',
    'auth.resetPassword': 'Réinitialiser le mot de passe',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.sendResetLink': 'Envoyer le lien',
    'auth.resendIn': 'Renvoyer dans',
    'auth.resend': 'Renvoyer',
    'auth.resetEmailSent': 'Un courriel de réinitialisation a été envoyé',
    'auth.checkEmail': 'Vérifiez votre boîte de réception',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.settings': 'Paramètres',
    'nav.help': 'Aide',
    'nav.privacy': 'Confidentialité',
    'nav.logout': 'Déconnexion',
    
    // Dashboard
    'dashboard.title': 'Optimisateur de descriptions de produits',
    'dashboard.subtitle': 'Analysez vos avis clients et générez des descriptions optimisées',
    'dashboard.generateWith': 'Optimiser une description',
    'dashboard.withReviews': 'avec avis',
    'dashboard.withReviewsDesc': 'Optimiser des descriptions à partir d\'avis clients',
    'dashboard.withoutReviews': 'sans avis',
    'dashboard.withoutReviewsDesc': 'Optimiser des descriptions avec des mots-clés',
    'dashboard.statistics': 'Statistiques',
    'dashboard.statisticsDesc': 'Consultez les performances et tendances',
    'dashboard.aiDisclaimer': "Cet outil utilise l'IA pour générer les descriptions et peut commettre des erreurs. Veuillez relire et vérifier les informations avant de les publier.",
    
    // Review Analysis
    'review.title': 'Optimiser une description avec avis',
    'review.titleWithout': 'Optimiser une description sans avis',
    'review.skuIdentification': 'Identification du produit',
    'review.skuDescription': 'ID du produit Shopify',
    'review.validate': 'Valider',
    'review.productToOptimize': 'Produit à optimiser',
    'review.errorRequired': 'Une réponse est requise',
    'review.errorRequiredFile': 'Vous devez téléverser un document',
    'review.errorProductId': 'L\'ID du produit doit contenir au moins 13 chiffres',
    'review.requiredFields': 'Champs obligatoires *',
    'review.submit': 'Envoyer',
    'review.removeFile': 'Supprimer le fichier',
    'review.adjustCommand': 'Entrez une commande pour ajuster la description',
    'review.keywordsTitle': 'Instructions supplémentaires',
    'review.keywordsDescWithout': 'Entrez une commande et des mots-clés pour optimiser la description sans avis',
    'review.skuPlaceholder': 'Ex: 1234567890123',
  'review.manual.titlePlaceholder': 'Ex : Nom du produit (ex. T-shirt Classique)',
  'review.manual.descriptionPlaceholder': 'Ex : Courte description du produit...',
  'review.manual.pricePlaceholder': 'Ex : 29.99',
  'review.manual.skuPlaceholder': 'Ex : SKU-12345',
  'review.manual.categoryPlaceholder': 'Ex : Vêtements',
  'review.manual.priceLabel': 'Prix *',
  'review.manual.skuLabel': 'SKU *',
  'review.createQuestion': 'Voulez-vous créer un nouveau produit sur Shopify ?',
  'review.yes': 'Oui',
  'review.no': 'Non',
    'review.sku': 'SKU',
    'review.productName': 'Nom du produit',
    'review.category': 'Catégorie',
    'review.currentDescription': 'Description actuelle',
    'review.optimizedDescription': 'Description optimisée',
    'review.uploadReviews': 'Téléversez les avis à analyser',
    'review.uploadReviewsDesc': 'Les avis doivent être en format .csv',
    'review.selectLanguages': 'Langues',
    'review.selectLanguagesDesc': 'Sélectionnez la ou les langues dans laquelle vous voulez générer une description optimisée',
    'review.optimize': 'Optimiser la description',
    'review.optimizing': 'Optimisation en cours...',
    'review.regenerate': 'Regénérer',
    'review.regenerating': 'Régénération en cours...',
    'review.required': 'Champs obligatoire',
    'review.enterPrompt': 'Entrez un prompt pour ajuster la description',
    'review.import': 'Importer des avis',
    'review.importProducts': 'Importer des produits',
    'review.generate': 'Générer la description',
    'review.selectReviews': 'Sélectionnez les avis à analyser',
    'review.selectProducts': 'Sélectionnez les produits',
    'review.selectLanguage': 'Sélectionnez la langue',
    'review.keywords': 'Mots-clés ou ligne directrice',
    'review.keywordsPlaceholder': 'Entrez des mots-clés ou une ligne directrice pour la génération...',
    'review.original': 'Description originale',
    'review.suggested': 'Description suggérée',
    'review.suggestedFr': 'Description suggérée (Français)',
    'review.suggestedEn': 'Description suggérée (Anglais)',
    'review.modify': 'Modifier',
    'review.history': 'Historique',
    'review.feedback': 'Évaluation',
    'review.publish': 'Publier sur Shopify',
    'review.publishing': 'Publication en cours...',
  'review.shopifyPreview': 'Aperçu Shopify :',
    'review.create': 'Créer le produit sur Shopify',
    'review.creating': 'Création en cours...',
    'review.dragDrop': 'Glissez-déposez un fichier CSV ou',
    'review.browse': 'parcourir',
    'review.back': 'Retour',
    'review.french': 'Français',
    'review.english': 'Anglais',
    'review.next': 'Suivant',
    'review.selectAll': 'Tout sélectionner',
    'review.stepImport': 'Importation',
    'review.stepSelect': 'Sélection',
    'review.stepLanguage': 'Langue',
    'review.stepLanguageKeywords': 'Langue et mots clés',
    'review.stepResult': 'Résultat',
    'review.analysisTitle': 'Justifications',
    'review.justifications': 'Justifications',
    'review.sourceQuestion': 'Le produit existe-t-il sur Shopify?',
    'review.sourceQuestionDesc': 'Sélectionnez une option pour continuer.',
    'review.sourceShopify': 'Oui, sur Shopify',
    'review.sourceManual': 'Non, entrer manuellement',
    
    // Feedback
    'feedback.select': 'Sélectionnez une évaluation',
    'feedback.5': 'Dépasse largement les attentes',
    'feedback.4': 'Dépasse les attentes',
    'feedback.3': 'Réponds aux attentes',
    'feedback.2': 'En-dessous des attentes',
    'feedback.1': 'Ne répond pas aux attentes',
    'feedback.thankYou': 'Merci pour votre évaluation !',
    
    // Statistics
    'stats.title': 'Statistiques',
    'stats.requests': 'Requêtes générées',
    'stats.filterDate': 'Filtrer par date',
    'stats.filterProduct': 'Catégorie de produit',
    'stats.filterRating': 'Note d\'évaluation',
    'stats.allRatings': 'Toutes les notes',
    'stats.generationMethod': 'Méthode de génération',
    'stats.correlationChart': 'Corrélation notes / catégories / méthode',
    'stats.export': 'Exporter le rapport',
    'stats.email': 'Envoyer par courriel',
    'stats.feedbackReport': 'Rapport de rétroaction',
    'stats.negativeReviews': 'Analyse des avis négatifs',
    'stats.trends': 'Tendances par catégorie de produit',
    'stats.performance': 'Performance et analyse',
    'stats.averageSatisfaction': 'Satisfaction moyenne',
    'stats.publishingRate': 'Taux de publication',
    'stats.count': 'Nombre',
    'stats.rating': 'Évaluation',
    'stats.sizingIssue': 'Problème de taille',
    'stats.mentionedTimes': 'Mentionné # fois',
    'stats.materialQuality': 'Qualité du matériau',
    'stats.delayedDelivery': 'Livraison retardée',
    
    // Product types
    'product.all': 'Tous les produits',
    'product.shoes': 'Souliers',
    'product.pants': 'Pantalons',
    'product.shorts': 'Shorts',
    'product.tshirts': 'T-shirts',
    'product.longsleeves': 'Chandails longs',
    'product.caps': 'Casquettes',
    'product.underwear': 'Sous-vêtements',
    'product.socks': 'Chaussettes',
    'product.boots': 'Bottes',
    
    // Settings
    'settings.title': 'Paramètres des descriptions',
    'settings.uploadFiles': 'Importer des fichiers d\'entraînement',
    'settings.uploadDescription': 'Importez des fichiers PDF pour entraîner le modèle',
    'settings.fileType': 'Type de fichier',
    'settings.inclusion': 'Inclusion',
    'settings.exclusion': 'Exclusion',
    'settings.example': 'Exemple',
    'settings.uploadedFiles': 'Fichiers importés',
    'settings.fileName': 'Nom du fichier',
    'settings.uploadDate': 'Date d\'importation',
    'settings.actions': 'Actions',
    'settings.delete': 'Supprimer',
    'settings.replace': 'Remplacer',
    'settings.dropbox.instructions': 'Déposez votre fichier PDF ici ou',
    'settings.dropbox.browse': 'parcourir',
    'settings.pdfOnly': 'PDF uniquement',
    'settings.loadError': 'Impossible de charger la liste des fichiers',
    'settings.uploadedSuccess': '{name} importé et indexé',
    'settings.uploadFailed': 'Échec de l\'upload: {msg}',
    'settings.fileDeleted': 'Fichier supprimé',
    'settings.deleteFailed': 'Échec de la suppression: {msg}',
    'settings.replaceComingSoon': 'Fonctionnalité de remplacement à venir',
    // Toasts & common
    'toast.error': 'Erreur',
    'toast.productNotFound': 'Produit non trouvé ou une erreur est survenue.',
    'toast.optimizeFailed': 'Une erreur est survenue lors de l\'optimisation. Il se peut que le modèle soit temporairement indisponible.',
    'toast.regenerateFailedTitle': 'Erreur de régénération',
    'toast.regenerateFailedDesc': 'Une erreur est survenue lors de la régénération.',
    'toast.publishSuccessTitle': 'Publication réussie',
    'toast.publishSuccessDesc': 'La description a été publiée sur Shopify',
    'toast.publishFailedTitle': 'Erreur de publication',
    'toast.publishFailedDesc': 'Une erreur est survenue lors de la publication sur Shopify.',
    'toast.missingProductDetails': 'Les détails du produit sont manquants.',
    'toast.createMissingFieldsTitle': 'Champs obligatoires manquants',
    'toast.createMissingFieldsDesc': 'Veuillez remplir les champs Price et SKU.',
    'toast.createSuccessTitle': 'Création réussie',
    'toast.createSuccessDesc': 'Le produit a été créé sur Shopify.',
    'toast.createFailedTitle': 'Erreur de création',
    'toast.createFailedDesc': 'Une erreur est survenue lors de la création du produit sur Shopify.',
    // Help / FAQ
    'help.title': 'Aide',
    'help.faq1.question': 'Comment importer mes avis clients?',
    'help.faq1.answer': 'Vous pouvez importer vos avis au format CSV via la fonction de glisser-déposer ou en cliquant sur le bouton "Parcourir".',
    'help.faq2.question': "Comment fonctionne l'analyse IA?",
    'help.faq2.answer': "L'IA analyse les avis clients pour identifier les points forts et les préoccupations, puis génère une description optimisée qui met en valeur votre produit.",
    'help.faq3.question': 'Puis-je modifier les descriptions générées?',
    'help.faq3.answer': 'Oui, vous pouvez éditer toute description générée avant de la publier. Un historique des modifications est conservé.',
    'help.faq4.question': 'Comment publier sur Shopify?',
    'help.faq4.answer': 'Après avoir donné votre évaluation, le bouton "Publier sur Shopify" devient actif. Cliquez dessus pour synchroniser la description avec votre boutique.',
    'help.contact.title': 'Contact',
    'help.contact.desc': 'Pour toute question supplémentaire, contactez notre équipe de support à support@exemple.com',
  },
  en: {
    // Auth
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.submit': 'Sign in',
    'auth.forgotPassword': 'I forgot my password',
    'auth.createAccount': 'I want to create my account',
    'auth.signup': 'Create account',
    'auth.resetPassword': 'Reset password',
    'auth.backToLogin': 'Back to login',
    'auth.sendResetLink': 'Send reset link',
    'auth.resendIn': 'Resend in',
    'auth.resend': 'Resend',
    'auth.resetEmailSent': 'A reset email has been sent',
    'auth.checkEmail': 'Check your inbox',
    'auth.confirmPassword': 'Confirm password',
    'auth.passwordMismatch': 'Passwords do not match',
    
    // Navigation
    'nav.home': 'Home',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.privacy': 'Privacy',
    'nav.logout': 'Log out',
    
    // Dashboard
    'dashboard.title': 'Product Description Optimizer',
    'dashboard.subtitle': 'Analyze your customer reviews and generate optimized descriptions',
    'dashboard.generateWith': 'Optimize a description',
    'dashboard.withReviews': 'with reviews',
    'dashboard.withReviewsDesc': 'Optimize descriptions based on customer reviews',
    'dashboard.withoutReviews': 'without reviews',
    'dashboard.withoutReviewsDesc': 'Optimize descriptions using keywords',
    'dashboard.statistics': 'Statistics',
    'dashboard.statisticsDesc': 'View performance and trends',
    'dashboard.aiDisclaimer': 'This tool uses AI to generate the descriptions and may make mistakes. Please review and verify information before publishing.',
    
    // Review Analysis
    'review.title': 'Optimize a description with reviews',
    'review.titleWithout': 'Optimize a description without reviews',
    'review.skuIdentification': 'Product identification',
    'review.skuDescription': 'Shopify Product ID',
    'review.validate': 'Submit',
    'review.productToOptimize': 'Product to Optimize',
    'review.errorRequired': 'A response is required',
    'review.errorRequiredFile': 'You must upload a document',
    'review.errorProductId': 'Product ID must contain at least 13 digits',
    'review.requiredFields': 'Required fields *',
    'review.submit': 'Submit',
    'review.removeFile': 'Remove file',
    'review.adjustCommand': 'Enter a command to adjust the description',
    'review.keywordsTitle': 'Additional instructions',
    'review.keywordsDescWithout': 'Enter a command and keywords to optimize the description without reviews',
    'review.skuPlaceholder': 'Ex: 1234567890123',
  'review.manual.titlePlaceholder': 'Ex: Product name (e.g., Classic Tee)',
  'review.manual.descriptionPlaceholder': 'Ex: Short product description...',
  'review.manual.pricePlaceholder': 'Ex: 29.99',
  'review.manual.skuPlaceholder': 'Ex: SKU-12345',
  'review.manual.categoryPlaceholder': 'Ex: Apparel',
  'review.manual.priceLabel': 'Price *',
  'review.manual.skuLabel': 'SKU *',
  'review.createQuestion': 'Would you like to create a new product on Shopify?',
  'review.yes': 'Yes',
  'review.no': 'No',
    'review.sku': 'SKU',
    'review.productName': 'Product name',
    'review.category': 'Category',
    'review.currentDescription': 'Current description',
    'review.optimizedDescription': 'Optimized description',
    'review.uploadReviews': 'Upload reviews to analyze',
    'review.uploadReviewsDesc': 'Reviews must be in .csv format',
    'review.selectLanguages': 'Languages',
    'review.selectLanguagesDesc': 'Select the language(s) in which you want to generate an optimized description',
    'review.optimize': 'Optimize the description',
    'review.optimizing': 'Optimizing...',
    'review.regenerate': 'Regenerate',
    'review.regenerating': 'Regenerating...',
    'review.required': 'Required field',
    'review.enterPrompt': 'Enter a prompt to adjust the description',
    'review.import': 'Import Reviews',
    'review.importProducts': 'Import Products',
    'review.generate': 'Generate description',
    'review.selectReviews': 'Select reviews to analyze',
    'review.selectProducts': 'Select products',
    'review.selectLanguage': 'Select language',
    'review.keywords': 'Keywords or guideline',
    'review.keywordsPlaceholder': 'Enter keywords or a guideline for generation...',
    'review.original': 'Original Description',
    'review.suggested': 'Suggested Description',
    'review.suggestedFr': 'Suggested Description (French)',
    'review.suggestedEn': 'Suggested Description (English)',
    'review.modify': 'Modify',
    'review.history': 'History',
    'review.feedback': 'Rating',
    'review.publish': 'Publish to Shopify',
    'review.publishing': 'Publishing...',
  'review.shopifyPreview': 'Shopify preview:',
    'review.create': 'Create Product on Shopify',
    'review.creating': 'Creating...',
    'review.dragDrop': 'Drag and drop a CSV file or',
    'review.browse': 'browse',
    'review.back': 'Back',
    'review.french': 'French',
    'review.english': 'English',
    'review.next': 'Next',
    'review.selectAll': 'Select All',
    'review.stepImport': 'Import',
    'review.stepSelect': 'Selection',
    'review.stepLanguage': 'Language',
    'review.stepLanguageKeywords': 'Language and Keywords',
    'review.stepResult': 'Result',
    'review.analysisTitle': 'Justifications',
    'review.justifications': 'Justifications',
    'review.sourceQuestion': 'Does the product exist on Shopify?',
    'review.sourceQuestionDesc': 'Select an option to continue.',
    'review.sourceShopify': 'Yes, on Shopify',
    'review.sourceManual': 'No, enter manually',
    
    // Feedback
    'feedback.select': 'Select a rating',
    'feedback.5': 'Far exceeds expectations',
    'feedback.4': 'Exceeds expectations',
    'feedback.3': 'Meets expectations',
    'feedback.2': 'Below expectations',
    'feedback.1': 'Does not meet expectations',
    'feedback.thankYou': 'Thank you for your feedback!',
    
    // Statistics
    'stats.title': 'Statistics',
    'stats.requests': 'Generated requests',
    'stats.filterDate': 'Filter by date',
    'stats.filterProduct': 'Product category',
    'stats.filterRating': 'Rating',
    'stats.allRatings': 'All ratings',
    'stats.generationMethod': 'Generation method',
    'stats.correlationChart': 'Correlation between ratings / categories / method',
    'stats.export': 'Export Report',
    'stats.email': 'Send by Email',
    'stats.feedbackReport': 'Feedback report',
    'stats.negativeReviews': 'Negative review analysis',
    'stats.trends': 'Trends by category of product',
    'stats.performance': 'Performance and analysis',
    'stats.averageSatisfaction': 'Average satisfaction',
    'stats.publishingRate': 'Publishing rate',
    'stats.count': 'Count',
    'stats.rating': 'Rating',
    'stats.sizingIssue': 'Sizing issue',
    'stats.mentionedTimes': 'Mentioned # times',
    'stats.materialQuality': 'Material quality',
    'stats.delayedDelivery': 'Delayed delivery',
    
    // Product types
    'product.all': 'All products',
    'product.shoes': 'Shoes',
    'product.pants': 'Pants',
    'product.shorts': 'Shorts',
    'product.tshirts': 'T-shirts',
    'product.longsleeves': 'Long-sleeve shirts',
    'product.caps': 'Caps',
    'product.underwear': 'Underwear',
    'product.socks': 'Socks',
    'product.boots': 'Boots',
    
    // Settings
    'settings.title': 'Description Settings',
    'settings.uploadFiles': 'Upload Training Files',
    'settings.uploadDescription': 'Upload PDF files to train the model',
    'settings.fileType': 'File Type',
    'settings.inclusion': 'Inclusion',
    'settings.exclusion': 'Exclusion',
    'settings.example': 'Example',
    'settings.uploadedFiles': 'Uploaded Files',
    'settings.fileName': 'File Name',
    'settings.uploadDate': 'Upload Date',
    'settings.actions': 'Actions',
    'settings.delete': 'Delete',
    'settings.replace': 'Replace',
    
    // Toasts & common
    'toast.error': 'Error',
    'toast.productNotFound': 'Product not found or an error occurred.',
    'toast.optimizeFailed': 'An error occurred during optimization. The model may be temporarily unavailable.',
    'toast.regenerateFailedTitle': 'Regeneration error',
    'toast.regenerateFailedDesc': 'An error occurred during regeneration.',
    'toast.publishSuccessTitle': 'Publish successful',
    'toast.publishSuccessDesc': 'The description was published to Shopify',
    'toast.publishFailedTitle': 'Publish error',
    'toast.publishFailedDesc': 'An error occurred while publishing to Shopify.',
    'toast.missingProductDetails': 'Product details are missing.',
    'toast.createMissingFieldsTitle': 'Missing required fields',
    'toast.createMissingFieldsDesc': 'Please fill Price and SKU fields.',
    'toast.createSuccessTitle': 'Creation successful',
    'toast.createSuccessDesc': 'The product was created on Shopify.',
    'toast.createFailedTitle': 'Creation error',
    'toast.createFailedDesc': 'An error occurred while creating the product on Shopify.',
    // Help / FAQ
    'help.title': 'Help',
    'help.faq1.question': 'How do I import my customer reviews?',
    'help.faq1.answer': 'You can import your reviews in CSV format via the drag-and-drop function or by clicking the "Browse" button.',
    'help.faq2.question': 'How does AI analysis work?',
    'help.faq2.answer': 'The AI analyzes customer reviews to identify strengths and concerns, then generates an optimized description that highlights your product.',
    'help.faq3.question': 'Can I edit generated descriptions?',
    'help.faq3.answer': 'Yes, you can edit any generated description before publishing it. A history of modifications is kept.',
    'help.faq4.question': 'How do I publish to Shopify?',
    'help.faq4.answer': 'After providing your feedback, the "Publish to Shopify" button becomes active. Click it to sync the description with your store.',
    'help.contact.title': 'Contact',
    'help.contact.desc': 'For any additional questions, contact our support team at support@example.com',
    'settings.dropbox.instructions': 'Drop your PDF file here or',
    'settings.dropbox.browse': 'browse',
    'settings.pdfOnly': 'PDF only',
    'settings.loadError': 'Unable to load file list',
    'settings.uploadedSuccess': '{name} imported and indexed',
    'settings.uploadFailed': 'Upload failed: {msg}',
    'settings.fileDeleted': 'File deleted',
    'settings.deleteFailed': 'Delete failed: {msg}',
    'settings.replaceComingSoon': 'Replace functionality coming soon',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
